version: '3.3'

services:

  anpr_dashboard_server:
    container_name: anpr_dashboard_server
    image: teamdigitale/anpr-dashboard-server

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    volumes:
    - ./development_demo_data/vault/config:/srv/anpr/vault/config
    - ./development_demo_data/vault/cookie-creds:/srv/anpr/vault/cookie-creds
    - ./development_demo_data/vault/email-creds:/srv/anpr/vault/email-creds
    - ./development_demo_data/vault/oauth-creds:/srv/anpr/vault/oauth-creds
    - ./development_demo_data/db:/srv/anpr/db
    - ./development_demo_data/cache:/var/cache/dashboard_scripts

    entrypoint:
    - "/srv/anpr/server/dashboard"
    - "--http-listen-on=[::]:8080"
    # Config file
    - "--config-file=/srv/anpr/vault/config/data.yaml"
    # Credentials
    - "--cookie-creds=/srv/anpr/vault/cookie-creds/data.json"
    - "--email-creds=/srv/anpr/vault/email-creds/data.yaml"
    - "--oauth-creds=/srv/anpr/vault/oauth-creds/data.yaml"
    # Other files embedded in the Docker image
    - "--web-templates=/srv/anpr/server/templates/"
    - "--email-templates=/srv/anpr/server/emails/"
    - "--static-content=/srv/anpr/server/static/"
